name: "Send a Slack Message using PHP"
author: nandagopal
description: "Send a slack message with workflow information"
inputs:
  slack_webhook:
    description: "Slack Webhook"
    required: true
  message:
    description: "Slack Message"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.slack_webhook }}
    - ${{ inputs.message }}
branding:
  icon: message-square
  color: purple
